apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pluralkit-gateway
spec:
  serviceName: pluralkit-gateway
  replicas: 3
  selector:
    matchLabels:
      app: pluralkit-gateway
  template:
    metadata:
      labels:
        app: pluralkit-gateway
    spec:
      containers:
      - name: gateway
        image: registry.den.vixen.lgbt/gateway:latest
        command: [ "/gateway" ]
        resources:
          requests:
            cpu: 1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: pluralkit-config-shared
        env:
        # Secrets
        - name: pluralkit__discord__bot_token
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: credential
        - name: pluralkit__db__db_password
          valueFrom:
            secretKeyRef:
              name: database-password
              key: credential
        - name: pluralkit__sentry_url
          valueFrom:
            secretKeyRef:
              name: dotnet-bot-sentry-url
              key: credential

        # Renamed
        - name: pluralkit__discord__cluster__total_shards
          valueFrom:
            configMapKeyRef:
              name: pluralkit-config-shared
              key: PluralKit__TotalShards
        
        # Misc
        - name: pluralkit__discord__max_concurrency
          value: '16'
        - name: pluralkit__runtime_config_key
          value: 'gateway-k8s'
        - name: STATEFULSET_NAME_FOR_INDEX # gets turned into node_id by rust code
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: pluralkit-gateway
spec:
  clusterIP: None
  selector:
    app: pluralkit-gateway
  ports:
  - port: 5000